[build]
    publish = "./dist"
    command = "npm run build"

[build.environment]
    DISABLE_PHONE_RECOVERY = "no"
    REACT_APP_NETWORK_ID = "testnet"
    REACT_APP_ACCOUNT_HELPER_URL = "https://helper.testnet.near.org"
    CONTRACT_HELPER_URL = "https://helper.testnet.near.org" # TODO: Consolidate to single env variable with REACT_APP_ACCOUNT_HELPER_URL
    REACT_APP_NODE_URL = "https://rpc.testnet.near.org"
    REACT_APP_ACCESS_KEY_FUNDING_AMOUNT = "250000000000000000000000"
    NEW_ACCOUNT_AMOUNT = "500000001000000000000000000"
    REACT_APP_ACCOUNT_ID_SUFFIX = "testnet"
    WAMP_NEAR_EXPLORER_URL = "wss://near-explorer-wamp.onrender.com/ws"
    WAMP_NEAR_EXPLORER_TOPIC_PREFIX = "com.nearprotocol.testnet.explorer"
    EXPLORER_URL = "https://explorer.testnet.near.org"
    REACT_APP_IS_MAINNET = "false"
    SHOW_PRERELEASE_WARNING = "yes"
    DISABLE_SEND_MONEY = "no"
    DISABLE_CREATE_ACCOUNT = "false"
    REACT_APP_MULTISIG_MIN_AMOUNT = "36"
    LOCKUP_ACCOUNT_ID_SUFFIX = "lockup.near"


[context.production.environment]
    SHOW_PRERELEASE_WARNING = "yes"
    MIXPANEL_TOKEN = "4a10180da7af8d6d0728154d535aa7bb"
    CONTRACT_NAME = "personas1.vitalpointai.testnet"
    PERSONAS_CONTRACT = "personas1.vitalpointai.testnet"
    DID_CONTRACT = "did.vitalpointai.testnet"
    DAO_CONTRACT = "near-dao.vitalpointai.testnet"
    DEFAULT_GAS_VALUE = "300000000000000"
    NODE_ENV = "testnet"
    APP_ID = "vp-personas"
    THREADDB_APPIDENTITY_STRING = "appid"
    THREADDB_APP_THREADID = "apptId"
    THREADDB_APPTOKEN_STRING = "apptok"
    THREADDB_IDENTITY_STRING = "id"
    THREADDB_USER_THREADID = "tId"
    THREADDB_TOKEN_STRING = "tok"
    APPID = "vp-personas"
    APP_TITLE = "Vital Point Personas"
    APP_TITLE_ID = "vppersona-memberId"

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "deny"
        Content-Security-Policy = """
            frame-ancestors 'none'
        """

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

